{
  "comments": [
    {
      "key": {
        "uuid": "c0cc5638_08b9494b",
        "filename": "scripts/geopmpy/io.py",
        "patchSetId": 1
      },
      "lineNbr": 115,
      "author": {
        "id": 1009284
      },
      "writtenOn": "2019-08-19T23:44:09Z",
      "side": 0,
      "message": "Was there a bug here, and in the trace logic below?",
      "range": {
        "startLine": 115,
        "startChar": 29,
        "endLine": 115,
        "endChar": 31
      },
      "revId": "242f921de948d460bc3aeb28ce2ff3dd5bce8816",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    }
  ]
}