{
  "comments": [
    {
      "key": {
        "uuid": "baa041b7_a6c44041",
        "filename": "test_integration/geopm_test_integration.py",
        "patchSetId": 6
      },
      "lineNbr": 453,
      "author": {
        "id": 1009284
      },
      "writtenOn": "2016-11-01T20:44:52Z",
      "side": 1,
      "message": "Attempts to handle the case when a node was idle when this test first checked, but was alloc\u0027d for work by someone else before the loop got here.",
      "range": {
        "startLine": 453,
        "startChar": 12,
        "endLine": 453,
        "endChar": 16
      },
      "revId": "ecb70fb94c92cc4775cc046d93a1a6df3bf33d6b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "baa041b7_86c13c32",
        "filename": "test_integration/geopm_test_integration.py",
        "patchSetId": 6
      },
      "lineNbr": 456,
      "author": {
        "id": 1009284
      },
      "writtenOn": "2016-11-01T20:44:52Z",
      "side": 1,
      "message": "The code is different if the job timeout expires.  I\u0027m only seeing 1 if resources weren\u0027t available.",
      "range": {
        "startLine": 456,
        "startChar": 19,
        "endLine": 456,
        "endChar": 36
      },
      "revId": "ecb70fb94c92cc4775cc046d93a1a6df3bf33d6b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}